name: Benchmarks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  matrix_bench:
      runs-on: ${{ matrix.platform.os }}
      strategy:
        matrix:
          platform:
            - {
                name: windows,
                target: x86_64-pc-windows-msvc,
                os: windows-latest,
              }
            - {
                name: macos,
                target: aarch64-apple-darwin,
                os: macos-latest,
              }
            - {
                name: linux,
                target: x86_64-unknown-linux-gnu,
                os: ubuntu-latest,
              }
          bench:
            - layout
            - text_shaping_benchmarks

      name: Test ${{ matrix.bench }} (${{ matrix.platform.name }})

      steps:
        - uses: actions/checkout@v4
        - name: install stable
          uses: dtolnay/rust-toolchain@master
          with:
            toolchain: stable
            targets: ${{ matrix.platform.target }}

        - name: Run Benchmarks
          run: cargo bench --bench ${{ matrix.bench }}
